spring:
  application:
    name: spring-security

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/db1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  h2:
    console:
      path: /h2-console
      enabled: false

token:
  signing:
    key: 322F4428472B4B6250655368566D5970337336763979244226452948404D6351
